[package]
name = "rs-whep-play"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.7.2"
tokio = "1.28.0"
anyhow = "1.0.71"
serde_json = "1.0.96"
reqwest = "0.11.17"
gstreamer = "0.20.5"
gstreamer-app = "0.20.0"
log = "0.4.17"
env_logger = "0.10.0"
