[package]
name = "rs-whep-play"
version = "0.1.0"
edition = "2021"
authors = ["Michel Promonet <michel.promonet@free.fr>"]
license = "The Unlicense"
keywords = ["webrtc", "whep", "gstreamer"]

[dependencies]
webrtc = "0.7.3"
tokio = "1.28.2"
anyhow = "1.0.71"
reqwest = "0.11.18"
gstreamer = "0.20.5"
gstreamer-app = "0.20.0"
log = "0.4.18"
env_logger = "0.10.0"
