[package]
name = "rs-whep-play"
version = "0.1.0"
edition = "2021"
authors = ["Michel Promonet <michel.promonet@free.fr>"]
license = "The Unlicense"
keywords = ["webrtc", "whep", "gstreamer"]

[dependencies]
webrtc = "0.8.0"
tokio = "1.29.1"
anyhow = "1.0.71"
reqwest = "0.11.18"
gstreamer = "0.21.0"
gstreamer-app = "0.21.0"
log = "0.4.19"
env_logger = "0.10.0"
