[package]
name = "rs-whep-play"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.7.2"
tokio = "1.28.0"
anyhow = "1.0.71"
signal = "0.7.0"
chrono = "0.4.24"
serde_json = "1.0.96"
reqwest = "0.11.17"